apiVersion: v1
kind: Pod
metadata:
    name: game-demo-pod
    labels:
        app: game-demo-pod
spec:
    containers:
        -   name: game-demo-pod
            image: ubuntu:latest
            command: [ "sleep" ]
            args: [ "3600" ]
            imagePullPolicy: IfNotPresent
            env:
                # Define the environment variable
                -   name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                    # from the key name in the ConfigMap.
                    valueFrom:
                        configMapKeyRef:
                            name: game-demo-configmap           # The ConfigMap this value comes from.
                            key: player_initial_lives # The key to fetch.
                -   name: UI_PROPERTIES_FILE_NAME
                    valueFrom:
                        configMapKeyRef:
                            name: game-demo-configmap
                            key: ui_properties_file_name
            volumeMounts:
                -   name: config
                    mountPath: "/config"
                    readOnly: true
    volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        -   name: config
            configMap:
                # Provide the name of the ConfigMap you want to mount.
                name: game-demo-configmap
                # An array of keys from the ConfigMap to create as files
                items:
                    -   key: "game.properties"
                        path: "game.properties"
                    -   key: "user-interface.properties"
                        path: "user-interface.properties"

    restartPolicy: Never
