apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-sleeper
    labels:
        app: ubuntu-sleeper
spec:
    containers:
        -   name: ubuntu-sleeper
            image: ubuntu
            imagePullPolicy: IfNotPresent
            securityContext:
                runAsUser: 1
                capabilities:
                    add:
                        - "SYS_TIME"
                        - "NET_ADMIN"
            command:
                - "sleep"
                - "3600"
    securityContext:
        runAsUser: 1010
    restartPolicy: Always
