apiVersion: v1
kind: Pod
metadata:
    name: redis
    namespace: finance
    labels:
        app: redis
spec:
    containers:
        -   name: redis
            image: redis
            imagePullPolicy: IfNotPresent
    restartPolicy: Always
