# Service

apiVersion: v1
kind: Service
metadata:
    name: myapp-service
spec:
    type: NodePort
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 80
    selector:
        app: myapp-deployment-nginx
