apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels:
        app: myapp-webserver
spec:
    containers:
        -   name: nginx-container
            image: nginx
            imagePullPolicy: IfNotPresent
    restartPolicy: Always
